services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./:/rails
    entrypoint: ["./bin/docker-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3030/up"]
      interval: 30s
      timeout: 2s
      retries: 3
    stdin_open: true
    tty: true
    restart: always
  whatsapp-api:
    image: "devlikeapro/waha"
    ports:
      - "3000:3000/tcp"
    environment:
      - WHATSAPP_API_PORT=3000
    restart: always
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/rails
    ports:
      - "80:80"
    depends_on:
      web:
        condition: service_healthy
    restart: always
        
